sudo: required
dist: trusty
language: cpp
compiler: gcc

before_install:
    - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended latexmk texlive-lang-german texlive-doc-de pgf texlive-font-utils zip inkscape texlive-math-extra graphviz make libsfml-dev libgtest-dev cmake
    - cd /usr/src/gtest
    - sudo cmake CMakeLists.txt
    - sudo make
    - sudo cp *.a /usr/lib
    - sudo ldconfig 
    - cd $TRAVIS_BUILD_DIR

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-7
        - g++-7
        - cmake
    sonarcloud:
        organization: "aul12-github" # the key of the org you chose at step #3
        token:
            secure: $SONAR_TOKEN # encrypted value of your token

script:
    - mkdir output
    - cd Blatt01
    - latexmk -pdf main.tex
    - mv main.pdf ../output/Blatt01.pdf
    - cd ..
    - cd Blatt02
    - make all
    - mv main.pdf ../output/Blatt02.pdf
    - cd ..
    - cd Blatt03
    - make all
    - mv main.pdf ../output/Blatt03.pdf
    - cd ..
    - cd Blatt04
    - make all
    - mv main.pdf ../output/Blatt04.pdf
    - cd ..
    - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
    - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
    - cd Blatt05
    - mkdir -p build
    - cd build
    - cmake ..
    - make all
    - ./Test
    - cd ..
    - sonar-scanner

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    local-dir: output
    on:
        branch: master
